version: "3.7"


services:
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    environment:
        - REDIS_PASSWORD=redis
        - REDIS_PORT=6379
        - REDIS_HOST=0.0.0.0

  celery:
    container_name: celery
    build:
        context: .
        dockerfile: docker/Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: celery -A celery_parsing worker -l INFO
    depends_on:
      - redis

  celery-beat:
    container_name: celery-beat
    build:
        context: .
        dockerfile: docker/Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: celery -A celery_parsing beat -l INFO -s data/celerybeat-schedule
    volumes:
      - ./data/:/app/data/
    depends_on:
      - celery