version: "3.7"

services:
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "${REDIS_PORT}:6379"
    environment:
       - REDIS_PASSWORD=${REDIS_PASSWORD}
       - REDIS_PORT=6379
       - REDIS_HOST=${REDIS_HOST}
    volumes:
      - redis_data:/data

  celery:
    container_name: celery
    build:
        context: ../
        dockerfile: docker/Dockerfile
    env_file:
      - ../.env
    environment:
      - REDIS_HOST=redis
    command: celery -A celery_parsing worker -l INFO
    depends_on:
      - redis

  celery-beat:
    container_name: celery-beat
    build:
        context: ../
        dockerfile: docker/Dockerfile
    env_file:
      - ../.env
    environment:
      - REDIS_HOST=redis
    command: celery -A celery_parsing beat -l INFO -s data/celerybeat-schedule
    depends_on:
      - celery

volumes:  
  redis_data:
